# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # Check for added large files. 
      - id: check-added-large-files
        args: [--maxkb=500]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.18
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/numpy/numpydoc
    rev: v1.10.0
    hooks:
      # Validate docstrings in the codebase
      - id: numpydoc-validation
        files: ^src/
        exclude: ^src/ptychobench/commulearn/

  - repo: local
    hooks:
      # Run the type checker.
      - id: ty
        name: ty
        entry: uv run ty check .
        language: system
        pass_filenames: false
        always_run: true
